var hierarchy =
[
    [ "v8::ActivityControl", "classv8_1_1_activity_control.html", null ],
    [ "v8::AllocationProfile::Allocation", "structv8_1_1_allocation_profile_1_1_allocation.html", null ],
    [ "v8::AllocationProfile", "classv8_1_1_allocation_profile.html", null ],
    [ "v8::ArrayBuffer::Allocator", "classv8_1_1_array_buffer_1_1_allocator.html", null ],
    [ "v8::Isolate::AllowJavascriptExecutionScope", "classv8_1_1_isolate_1_1_allow_javascript_execution_scope.html", null ],
    [ "v8::internal::Arguments< ArgumentsType >", "classv8_1_1internal_1_1_arguments.html", null ],
    [ "v8::platform::tracing::TraceObject::ArgValue", "unionv8_1_1platform_1_1tracing_1_1_trace_object_1_1_arg_value.html", null ],
    [ "v8::Isolate::AtomicsWaitWakeHandle", "classv8_1_1_isolate_1_1_atomics_wait_wake_handle.html", null ],
    [ "v8::internal::BackingStoreBase", "classv8_1_1internal_1_1_backing_store_base.html", [
      [ "v8::BackingStore", "classv8_1_1_backing_store.html", null ]
    ] ],
    [ "v8::Context::BackupIncumbentScope", "classv8_1_1_context_1_1_backup_incumbent_scope.html", null ],
    [ "cppgc::internal::BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy >", "classcppgc_1_1internal_1_1_basic_member.html", null ],
    [ "cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >", "classcppgc_1_1internal_1_1_basic_persistent.html", null ],
    [ "v8::ScriptCompiler::CachedData", "structv8_1_1_script_compiler_1_1_cached_data.html", null ],
    [ "v8::internal::CastCheck< PerformCheck >", "structv8_1_1internal_1_1_cast_check.html", null ],
    [ "v8::CFunction", "classv8_1_1_c_function.html", null ],
    [ "v8::CFunctionInfo", "classv8_1_1_c_function_info.html", [
      [ "v8::internal::CFunctionInfoImpl< R, Args >", "classv8_1_1internal_1_1_c_function_info_impl.html", null ]
    ] ],
    [ "v8_inspector::V8Inspector::Channel", "classv8__inspector_1_1_v8_inspector_1_1_channel.html", null ],
    [ "v8::WasmStreaming::Client", "classv8_1_1_wasm_streaming_1_1_client.html", null ],
    [ "v8::CodeEvent", "classv8_1_1_code_event.html", null ],
    [ "v8::CodeEventHandler", "classv8_1_1_code_event_handler.html", null ],
    [ "v8::CompiledWasmModule", "classv8_1_1_compiled_wasm_module.html", null ],
    [ "v8::SharedArrayBuffer::Contents", "classv8_1_1_shared_array_buffer_1_1_contents.html", null ],
    [ "v8::ArrayBuffer::Contents", "classv8_1_1_array_buffer_1_1_contents.html", null ],
    [ "v8::Context", "classv8_1_1_context.html", null ],
    [ "v8::ConvertableToTraceFormat", "classv8_1_1_convertable_to_trace_format.html", null ],
    [ "v8::CopyablePersistentTraits< T >", "structv8_1_1_copyable_persistent_traits.html", null ],
    [ "v8::CopyablePersistentTraits< v8::Context >", "structv8_1_1_copyable_persistent_traits.html", null ],
    [ "v8::CpuProfile", "classv8_1_1_cpu_profile.html", null ],
    [ "v8::CpuProfileDeoptFrame", "structv8_1_1_cpu_profile_deopt_frame.html", null ],
    [ "v8::CpuProfileDeoptInfo", "structv8_1_1_cpu_profile_deopt_info.html", null ],
    [ "v8::CpuProfileNode", "classv8_1_1_cpu_profile_node.html", null ],
    [ "v8::CpuProfiler", "classv8_1_1_cpu_profiler.html", null ],
    [ "v8::CpuProfilingOptions", "classv8_1_1_cpu_profiling_options.html", null ],
    [ "v8::Isolate::CreateParams", "structv8_1_1_isolate_1_1_create_params.html", null ],
    [ "v8::CTypeInfo", "classv8_1_1_c_type_info.html", null ],
    [ "v8::internal::CustomArguments< T >", "classv8_1_1internal_1_1_custom_arguments.html", null ],
    [ "cppgc::CustomSpaceBase", "classcppgc_1_1_custom_space_base.html", [
      [ "cppgc::CustomSpace< ConcreteCustomSpace >", "classcppgc_1_1_custom_space.html", null ]
    ] ],
    [ "cppgc::CustomSpaceIndex", "structcppgc_1_1_custom_space_index.html", null ],
    [ "v8::Data", "classv8_1_1_data.html", [
      [ "v8::AccessorSignature", "classv8_1_1_accessor_signature.html", null ],
      [ "v8::Module", "classv8_1_1_module.html", null ],
      [ "v8::Private", "classv8_1_1_private.html", null ],
      [ "v8::Signature", "classv8_1_1_signature.html", null ],
      [ "v8::Template", "classv8_1_1_template.html", [
        [ "v8::FunctionTemplate", "classv8_1_1_function_template.html", null ],
        [ "v8::ObjectTemplate", "classv8_1_1_object_template.html", null ]
      ] ],
      [ "v8::UnboundModuleScript", "classv8_1_1_unbound_module_script.html", null ],
      [ "v8::Value", "classv8_1_1_value.html", [
        [ "v8::External", "classv8_1_1_external.html", null ],
        [ "v8::Object", "classv8_1_1_object.html", [
          [ "v8::Array", "classv8_1_1_array.html", null ],
          [ "v8::ArrayBuffer", "classv8_1_1_array_buffer.html", null ],
          [ "v8::ArrayBufferView", "classv8_1_1_array_buffer_view.html", [
            [ "v8::DataView", "classv8_1_1_data_view.html", null ],
            [ "v8::TypedArray", "classv8_1_1_typed_array.html", [
              [ "v8::BigInt64Array", "classv8_1_1_big_int64_array.html", null ],
              [ "v8::BigUint64Array", "classv8_1_1_big_uint64_array.html", null ],
              [ "v8::Float32Array", "classv8_1_1_float32_array.html", null ],
              [ "v8::Float64Array", "classv8_1_1_float64_array.html", null ],
              [ "v8::Int16Array", "classv8_1_1_int16_array.html", null ],
              [ "v8::Int32Array", "classv8_1_1_int32_array.html", null ],
              [ "v8::Int8Array", "classv8_1_1_int8_array.html", null ],
              [ "v8::Uint16Array", "classv8_1_1_uint16_array.html", null ],
              [ "v8::Uint32Array", "classv8_1_1_uint32_array.html", null ],
              [ "v8::Uint8Array", "classv8_1_1_uint8_array.html", null ],
              [ "v8::Uint8ClampedArray", "classv8_1_1_uint8_clamped_array.html", null ]
            ] ]
          ] ],
          [ "v8::BigIntObject", "classv8_1_1_big_int_object.html", null ],
          [ "v8::BooleanObject", "classv8_1_1_boolean_object.html", null ],
          [ "v8::Date", "classv8_1_1_date.html", null ],
          [ "v8::Function", "classv8_1_1_function.html", null ],
          [ "v8::Map", "classv8_1_1_map.html", null ],
          [ "v8::NumberObject", "classv8_1_1_number_object.html", null ],
          [ "v8::Promise", "classv8_1_1_promise.html", null ],
          [ "v8::Promise::Resolver", "classv8_1_1_promise_1_1_resolver.html", null ],
          [ "v8::Proxy", "classv8_1_1_proxy.html", null ],
          [ "v8::RegExp", "classv8_1_1_reg_exp.html", null ],
          [ "v8::Set", "classv8_1_1_set.html", null ],
          [ "v8::SharedArrayBuffer", "classv8_1_1_shared_array_buffer.html", null ],
          [ "v8::StringObject", "classv8_1_1_string_object.html", null ],
          [ "v8::SymbolObject", "classv8_1_1_symbol_object.html", null ],
          [ "v8::WasmModuleObject", "classv8_1_1_wasm_module_object.html", null ]
        ] ],
        [ "v8::Primitive", "classv8_1_1_primitive.html", [
          [ "v8::BigInt", "classv8_1_1_big_int.html", null ],
          [ "v8::Boolean", "classv8_1_1_boolean.html", null ],
          [ "v8::Name", "classv8_1_1_name.html", [
            [ "v8::String", "classv8_1_1_string.html", null ],
            [ "v8::Symbol", "classv8_1_1_symbol.html", null ]
          ] ],
          [ "v8::Number", "classv8_1_1_number.html", [
            [ "v8::Integer", "classv8_1_1_integer.html", [
              [ "v8::Int32", "classv8_1_1_int32.html", null ],
              [ "v8::Uint32", "classv8_1_1_uint32.html", null ]
            ] ]
          ] ]
        ] ]
      ] ]
    ] ],
    [ "v8::DefaultPersistentValueVectorTraits", "classv8_1_1_default_persistent_value_vector_traits.html", null ],
    [ "v8::ValueSerializer::Delegate", "classv8_1_1_value_serializer_1_1_delegate.html", null ],
    [ "v8::ValueDeserializer::Delegate", "classv8_1_1_value_deserializer_1_1_delegate.html", null ],
    [ "v8::DeserializeInternalFieldsCallback", "structv8_1_1_deserialize_internal_fields_callback.html", null ],
    [ "cppgc::internal::DijkstraWriteBarrierPolicy", "structcppgc_1_1internal_1_1_dijkstra_write_barrier_policy.html", null ],
    [ "cppgc::internal::DisabledCheckingPolicy", "classcppgc_1_1internal_1_1_disabled_checking_policy.html", null ],
    [ "v8::Isolate::DisallowJavascriptExecutionScope", "classv8_1_1_isolate_1_1_disallow_javascript_execution_scope.html", null ],
    [ "cppgc::internal::EatParams< typename >", "structcppgc_1_1internal_1_1_eat_params.html", null ],
    [ "v8::EmbedderGraph", "classv8_1_1_embedder_graph.html", null ],
    [ "v8::EmbedderHeapTracer", "classv8_1_1_embedder_heap_tracer.html", null ],
    [ "enable_shared_from_this", null, [
      [ "v8_inspector::V8Inspector::Counters", "classv8__inspector_1_1_v8_inspector_1_1_counters.html", null ]
    ] ],
    [ "cppgc::internal::EnabledCheckingPolicy", "classcppgc_1_1internal_1_1_enabled_checking_policy.html", null ],
    [ "v8::internal::EnableIfHasWrapperTypeInfo< T, typename >", "structv8_1_1internal_1_1_enable_if_has_wrapper_type_info.html", null ],
    [ "v8::internal::EnableIfHasWrapperTypeInfo< T, decltype(WrapperTraits< T >::GetTypeInfo(), void())>", "structv8_1_1internal_1_1_enable_if_has_wrapper_type_info_3_01_t_00_01decltype_07_wrapper_traits_ed7af4adc480e3ae3cda6614840f5181.html", null ],
    [ "v8::Eternal< T >", "classv8_1_1_eternal.html", null ],
    [ "v8::Exception", "classv8_1_1_exception.html", null ],
    [ "v8::Extension", "classv8_1_1_extension.html", null ],
    [ "v8::ExtensionConfiguration", "classv8_1_1_extension_configuration.html", null ],
    [ "v8::ExternalResourceVisitor", "classv8_1_1_external_resource_visitor.html", null ],
    [ "v8::ScriptCompiler::ExternalSourceStream", "classv8_1_1_script_compiler_1_1_external_source_stream.html", null ],
    [ "v8::String::ExternalStringResourceBase", "classv8_1_1_string_1_1_external_string_resource_base.html", [
      [ "v8::String::ExternalOneByteStringResource", "classv8_1_1_string_1_1_external_one_byte_string_resource.html", null ],
      [ "v8::String::ExternalStringResource", "classv8_1_1_string_1_1_external_string_resource.html", null ]
    ] ],
    [ "false_type", null, [
      [ "cppgc::internal::HasFinalizeGarbageCollectedObject< T, typename >", "structcppgc_1_1internal_1_1_has_finalize_garbage_collected_object.html", null ],
      [ "cppgc::internal::IsGarbageCollectedMixinType< T, typename >", "structcppgc_1_1internal_1_1_is_garbage_collected_mixin_type.html", null ],
      [ "cppgc::internal::IsTraceable< T, typename >", "structcppgc_1_1internal_1_1_is_traceable.html", null ],
      [ "cppgc::internal::IsTraceMethodConst< T, typename >", "structcppgc_1_1internal_1_1_is_trace_method_const.html", null ],
      [ "cppgc::internal::IsWeak< T >", "structcppgc_1_1internal_1_1_is_weak.html", null ],
      [ "cppgc::internal::IsGarbageCollectedMixinType< T >", "structcppgc_1_1internal_1_1_is_garbage_collected_mixin_type.html", [
        [ "cppgc::internal::IsGarbageCollectedType< T, typename >", "structcppgc_1_1internal_1_1_is_garbage_collected_type.html", null ]
      ] ]
    ] ],
    [ "cppgc::internal::FinalizerTrait< T >", "structcppgc_1_1internal_1_1_finalizer_trait.html", null ],
    [ "cppgc::internal::FinalizerTraitImpl< T, isFinalized >", "structcppgc_1_1internal_1_1_finalizer_trait_impl.html", null ],
    [ "cppgc::internal::FinalizerTraitImpl< T, false >", "structcppgc_1_1internal_1_1_finalizer_trait_impl_3_01_t_00_01false_01_4.html", null ],
    [ "cppgc::internal::FinalizerTraitImpl< T, true >", "structcppgc_1_1internal_1_1_finalizer_trait_impl_3_01_t_00_01true_01_4.html", null ],
    [ "v8::FunctionCallbackInfo< T >", "classv8_1_1_function_callback_info.html", null ],
    [ "cppgc::internal::GarbageCollectedBase", "classcppgc_1_1internal_1_1_garbage_collected_base.html", [
      [ "cppgc::GarbageCollected< typename >", "classcppgc_1_1_garbage_collected.html", null ],
      [ "cppgc::GarbageCollectedMixin", "classcppgc_1_1_garbage_collected_mixin.html", null ]
    ] ],
    [ "cppgc::internal::GCInfoTrait< T >", "structcppgc_1_1internal_1_1_g_c_info_trait.html", null ],
    [ "v8::internal::GetCType< T >", "structv8_1_1internal_1_1_get_c_type.html", null ],
    [ "v8::internal::GetCTypePointerImpl< T, typename >", "structv8_1_1internal_1_1_get_c_type_pointer_impl.html", null ],
    [ "v8::internal::GetCTypePointerImpl< T >", "structv8_1_1internal_1_1_get_c_type_pointer_impl.html", [
      [ "v8::internal::GetCType< T * >", "structv8_1_1internal_1_1_get_c_type_3_01_t_01_5_01_4.html", null ]
    ] ],
    [ "v8::internal::GetCTypePointerImpl< T, typename EnableIfHasWrapperTypeInfo< T >::type >", "structv8_1_1internal_1_1_get_c_type_pointer_impl_3_01_t_00_01typename_01_enable_if_has_wrapper_t4180550b838684d950685e0c0cf3a19c.html", null ],
    [ "v8::internal::GetCTypePointerPointerImpl< T, typename >", "structv8_1_1internal_1_1_get_c_type_pointer_pointer_impl.html", null ],
    [ "v8::internal::GetCTypePointerPointerImpl< T >", "structv8_1_1internal_1_1_get_c_type_pointer_pointer_impl.html", [
      [ "v8::internal::GetCType< T ** >", "structv8_1_1internal_1_1_get_c_type_3_01_t_01_5_5_01_4.html", null ]
    ] ],
    [ "v8::internal::GetCTypePointerPointerImpl< T, typename EnableIfHasWrapperTypeInfo< T >::type >", "structv8_1_1internal_1_1_get_c_type_pointer_pointer_impl_3_01_t_00_01typename_01_enable_if_has_wf2e94d61b2f9de07d323b75d1a224215.html", null ],
    [ "v8::Global< T >", "classv8_1_1_global.html", null ],
    [ "v8::HandleScope", "classv8_1_1_handle_scope.html", [
      [ "v8::EscapableHandleScope", "classv8_1_1_escapable_handle_scope.html", null ]
    ] ],
    [ "cppgc::Heap", "classcppgc_1_1_heap.html", null ],
    [ "v8::HeapCodeStatistics", "classv8_1_1_heap_code_statistics.html", null ],
    [ "v8::HeapGraphEdge", "classv8_1_1_heap_graph_edge.html", null ],
    [ "v8::HeapGraphNode", "classv8_1_1_heap_graph_node.html", null ],
    [ "v8::HeapObjectStatistics", "classv8_1_1_heap_object_statistics.html", null ],
    [ "cppgc::Heap::HeapOptions", "structcppgc_1_1_heap_1_1_heap_options.html", null ],
    [ "v8::HeapProfiler", "classv8_1_1_heap_profiler.html", null ],
    [ "v8::HeapSnapshot", "classv8_1_1_heap_snapshot.html", null ],
    [ "v8::HeapSpaceStatistics", "classv8_1_1_heap_space_statistics.html", null ],
    [ "v8::HeapStatistics", "classv8_1_1_heap_statistics.html", null ],
    [ "v8::HeapStatsUpdate", "structv8_1_1_heap_stats_update.html", null ],
    [ "v8::IdleTask", "classv8_1_1_idle_task.html", null ],
    [ "cppgc::internal::IgnoreLocationPolicy", "classcppgc_1_1internal_1_1_ignore_location_policy.html", null ],
    [ "v8::IndexedPropertyHandlerConfiguration", "structv8_1_1_indexed_property_handler_configuration.html", null ],
    [ "v8_inspector::V8InspectorSession::Inspectable", "classv8__inspector_1_1_v8_inspector_session_1_1_inspectable.html", null ],
    [ "v8::internal::Internals", "classv8_1_1internal_1_1_internals.html", null ],
    [ "v8::Isolate", "classv8_1_1_isolate.html", null ],
    [ "cppgc::internal::IsSubclassOfTemplate< T, U >", "structcppgc_1_1internal_1_1_is_subclass_of_template.html", null ],
    [ "v8::JitCodeEvent", "structv8_1_1_jit_code_event.html", null ],
    [ "v8::JobDelegate", "classv8_1_1_job_delegate.html", null ],
    [ "v8::JobHandle", "classv8_1_1_job_handle.html", null ],
    [ "v8::JobTask", "classv8_1_1_job_task.html", null ],
    [ "v8::JSEntryStub", "structv8_1_1_j_s_entry_stub.html", null ],
    [ "v8::JSEntryStubs", "structv8_1_1_j_s_entry_stubs.html", null ],
    [ "v8::JSON", "classv8_1_1_j_s_o_n.html", null ],
    [ "cppgc::internal::KeepLocationPolicy", "classcppgc_1_1internal_1_1_keep_location_policy.html", null ],
    [ "v8::JitCodeEvent::line_info_t", "structv8_1_1_jit_code_event_1_1line__info__t.html", null ],
    [ "v8::CpuProfileNode::LineTick", "structv8_1_1_cpu_profile_node_1_1_line_tick.html", null ],
    [ "cppgc::LivenessBroker", "classcppgc_1_1_liveness_broker.html", null ],
    [ "v8::Local< T >", "classv8_1_1_local.html", null ],
    [ "v8::Local< Name >", "classv8_1_1_local.html", null ],
    [ "v8::Local< v8::Context >", "classv8_1_1_local.html", null ],
    [ "v8::Local< v8::Integer >", "classv8_1_1_local.html", null ],
    [ "v8::Local< v8::PrimitiveArray >", "classv8_1_1_local.html", null ],
    [ "v8::Local< v8::Promise >", "classv8_1_1_local.html", null ],
    [ "v8::Local< v8::String >", "classv8_1_1_local.html", null ],
    [ "v8::Local< v8::UnboundScript >", "classv8_1_1_local.html", null ],
    [ "v8::Local< v8::Value >", "classv8_1_1_local.html", null ],
    [ "v8::Local< Value >", "classv8_1_1_local.html", null ],
    [ "v8::Location", "classv8_1_1_location.html", null ],
    [ "v8::Locker", "classv8_1_1_locker.html", null ],
    [ "cppgc::internal::make_void< Ts >", "structcppgc_1_1internal_1_1make__void.html", null ],
    [ "cppgc::MakeGarbageCollectedTraitBase< T >", "classcppgc_1_1_make_garbage_collected_trait_base.html", [
      [ "cppgc::MakeGarbageCollectedTrait< T >", "classcppgc_1_1_make_garbage_collected_trait.html", null ]
    ] ],
    [ "cppgc::internal::MakeGarbageCollectedTraitInternal", "classcppgc_1_1internal_1_1_make_garbage_collected_trait_internal.html", null ],
    [ "v8::Maybe< T >", "classv8_1_1_maybe.html", null ],
    [ "v8::Maybe< void >", "classv8_1_1_maybe_3_01void_01_4.html", null ],
    [ "v8::MaybeLocal< T >", "classv8_1_1_maybe_local.html", null ],
    [ "v8::MaybeLocal< v8::String >", "classv8_1_1_maybe_local.html", null ],
    [ "v8::MeasureMemoryDelegate", "classv8_1_1_measure_memory_delegate.html", null ],
    [ "v8::MemoryRange", "structv8_1_1_memory_range.html", null ],
    [ "v8::MemorySpan< T >", "classv8_1_1_memory_span.html", null ],
    [ "v8::Message", "classv8_1_1_message.html", null ],
    [ "v8::MicrotaskQueue", "classv8_1_1_microtask_queue.html", null ],
    [ "v8::MicrotasksScope", "classv8_1_1_microtasks_scope.html", null ],
    [ "v8::ModifyCodeGenerationFromStringsResult", "structv8_1_1_modify_code_generation_from_strings_result.html", null ],
    [ "v8::JitCodeEvent::name_t", "structv8_1_1_jit_code_event_1_1name__t.html", null ],
    [ "v8::NamedPropertyHandlerConfiguration", "structv8_1_1_named_property_handler_configuration.html", null ],
    [ "v8::AllocationProfile::Node", "structv8_1_1_allocation_profile_1_1_node.html", null ],
    [ "v8::EmbedderGraph::Node", "classv8_1_1_embedder_graph_1_1_node.html", null ],
    [ "v8::NonCopyablePersistentTraits< T >", "classv8_1_1_non_copyable_persistent_traits.html", null ],
    [ "cppgc::internal::NoWriteBarrierPolicy", "structcppgc_1_1internal_1_1_no_write_barrier_policy.html", null ],
    [ "v8::HeapProfiler::ObjectNameResolver", "classv8_1_1_heap_profiler_1_1_object_name_resolver.html", null ],
    [ "v8::OutputStream", "classv8_1_1_output_stream.html", null ],
    [ "v8::OwnedBuffer", "structv8_1_1_owned_buffer.html", null ],
    [ "v8::PageAllocator", "classv8_1_1_page_allocator.html", null ],
    [ "v8::Persistent< T, M >", "classv8_1_1_persistent.html", null ],
    [ "v8::Persistent< v8::Promise >", "classv8_1_1_persistent.html", null ],
    [ "v8::PersistentBase< T >", "classv8_1_1_persistent_base.html", null ],
    [ "v8::PersistentHandleVisitor", "classv8_1_1_persistent_handle_visitor.html", null ],
    [ "cppgc::internal::PersistentNode", "classcppgc_1_1internal_1_1_persistent_node.html", null ],
    [ "cppgc::internal::PersistentRegion", "classcppgc_1_1internal_1_1_persistent_region.html", null ],
    [ "v8::PersistentValueMapBase< K, V, Traits >", "classv8_1_1_persistent_value_map_base.html", [
      [ "v8::GlobalValueMap< K, V, Traits >", "classv8_1_1_global_value_map.html", null ],
      [ "v8::PersistentValueMap< K, V, Traits >", "classv8_1_1_persistent_value_map.html", null ]
    ] ],
    [ "v8::PersistentValueMapBase< K, V, DefaultGlobalMapTraits< K, V > >", "classv8_1_1_persistent_value_map_base.html", [
      [ "v8::GlobalValueMap< K, V, DefaultGlobalMapTraits< K, V > >", "classv8_1_1_global_value_map.html", [
        [ "v8::StdGlobalValueMap< K, V, Traits >", "classv8_1_1_std_global_value_map.html", null ]
      ] ]
    ] ],
    [ "v8::PersistentValueMapBase< K, V, DefaultPersistentValueMapTraits< K, V > >", "classv8_1_1_persistent_value_map_base.html", [
      [ "v8::PersistentValueMap< K, V, DefaultPersistentValueMapTraits< K, V > >", "classv8_1_1_persistent_value_map.html", [
        [ "v8::StdPersistentValueMap< K, V, Traits >", "classv8_1_1_std_persistent_value_map.html", null ]
      ] ]
    ] ],
    [ "v8::PersistentValueMapBase< K, V, Traits >::PersistentValueReference", "classv8_1_1_persistent_value_map_base_1_1_persistent_value_reference.html", null ],
    [ "v8::PersistentValueVector< V, Traits >", "classv8_1_1_persistent_value_vector.html", null ],
    [ "v8::Platform", "classv8_1_1_platform.html", null ],
    [ "cppgc::PostConstructionCallbackTrait< T, typename >", "structcppgc_1_1_post_construction_callback_trait.html", null ],
    [ "cppgc::internal::PreFinalizerRegistrationDispatcher::PreFinalizer", "structcppgc_1_1internal_1_1_pre_finalizer_registration_dispatcher_1_1_pre_finalizer.html", null ],
    [ "cppgc::internal::PrefinalizerRegistration< T >", "classcppgc_1_1internal_1_1_prefinalizer_registration.html", null ],
    [ "cppgc::internal::PreFinalizerRegistrationDispatcher", "classcppgc_1_1internal_1_1_pre_finalizer_registration_dispatcher.html", null ],
    [ "v8::PrimitiveArray", "classv8_1_1_primitive_array.html", null ],
    [ "v8::PromiseRejectMessage", "classv8_1_1_promise_reject_message.html", null ],
    [ "v8::PropertyCallbackInfo< T >", "classv8_1_1_property_callback_info.html", null ],
    [ "v8::PropertyCallbackInfo< Array >", "classv8_1_1_property_callback_info.html", null ],
    [ "v8::PropertyCallbackInfo< Boolean >", "classv8_1_1_property_callback_info.html", null ],
    [ "v8::PropertyCallbackInfo< Integer >", "classv8_1_1_property_callback_info.html", null ],
    [ "v8::PropertyCallbackInfo< Value >", "classv8_1_1_property_callback_info.html", null ],
    [ "v8::PropertyDescriptor", "classv8_1_1_property_descriptor.html", null ],
    [ "cppgc::internal::RegisteredGCInfoIndex", "classcppgc_1_1internal_1_1_registered_g_c_info_index.html", null ],
    [ "v8::RegisterState", "structv8_1_1_register_state.html", null ],
    [ "v8::ResourceConstraints", "classv8_1_1_resource_constraints.html", null ],
    [ "v8::ReturnValue< T >", "classv8_1_1_return_value.html", null ],
    [ "v8::Isolate::SafeForTerminationScope", "classv8_1_1_isolate_1_1_safe_for_termination_scope.html", null ],
    [ "v8::AllocationProfile::Sample", "structv8_1_1_allocation_profile_1_1_sample.html", null ],
    [ "v8::SampleInfo", "structv8_1_1_sample_info.html", null ],
    [ "v8::Context::Scope", "classv8_1_1_context_1_1_scope.html", null ],
    [ "v8::Isolate::Scope", "classv8_1_1_isolate_1_1_scope.html", null ],
    [ "v8::Script", "classv8_1_1_script.html", null ],
    [ "v8::ScriptCompiler", "classv8_1_1_script_compiler.html", null ],
    [ "v8::ScriptOrigin", "classv8_1_1_script_origin.html", null ],
    [ "v8::ScriptOriginOptions", "classv8_1_1_script_origin_options.html", null ],
    [ "v8::ScriptOrModule", "classv8_1_1_script_or_module.html", null ],
    [ "v8::ScriptCompiler::ScriptStreamingTask", "classv8_1_1_script_compiler_1_1_script_streaming_task.html", null ],
    [ "v8::SealHandleScope", "classv8_1_1_seal_handle_scope.html", null ],
    [ "cppgc::internal::SentinelPointer", "structcppgc_1_1internal_1_1_sentinel_pointer.html", null ],
    [ "v8::SerializeInternalFieldsCallback", "structv8_1_1_serialize_internal_fields_callback.html", null ],
    [ "v8::SharedMemoryStatistics", "classv8_1_1_shared_memory_statistics.html", null ],
    [ "v8::internal::SmiTagging< tagged_ptr_size >", "structv8_1_1internal_1_1_smi_tagging.html", null ],
    [ "v8::internal::SmiTagging< 4 >", "structv8_1_1internal_1_1_smi_tagging_3_014_01_4.html", null ],
    [ "v8::internal::SmiTagging< 8 >", "structv8_1_1internal_1_1_smi_tagging_3_018_01_4.html", null ],
    [ "v8::SnapshotCreator", "classv8_1_1_snapshot_creator.html", null ],
    [ "v8::ScriptCompiler::Source", "classv8_1_1_script_compiler_1_1_source.html", null ],
    [ "cppgc::SourceLocation", "classcppgc_1_1_source_location.html", null ],
    [ "cppgc::SpaceTrait< T, typename >", "structcppgc_1_1_space_trait.html", null ],
    [ "v8::StackFrame", "classv8_1_1_stack_frame.html", null ],
    [ "v8::StackTrace", "classv8_1_1_stack_trace.html", null ],
    [ "v8::StartupData", "classv8_1_1_startup_data.html", null ],
    [ "v8::StdMapTraits< K, V >", "classv8_1_1_std_map_traits.html", [
      [ "v8::DefaultGlobalMapTraits< K, V >", "classv8_1_1_default_global_map_traits.html", null ],
      [ "v8::DefaultPersistentValueMapTraits< K, V >", "classv8_1_1_default_persistent_value_map_traits.html", null ]
    ] ],
    [ "v8::ScriptCompiler::StreamedSource", "classv8_1_1_script_compiler_1_1_streamed_source.html", null ],
    [ "v8_inspector::StringBuffer", "classv8__inspector_1_1_string_buffer.html", null ],
    [ "v8_inspector::StringView", "classv8__inspector_1_1_string_view.html", null ],
    [ "cppgc::internal::StrongPersistentPolicy", "structcppgc_1_1internal_1_1_strong_persistent_policy.html", null ],
    [ "v8::Isolate::SuppressMicrotaskExecutionScope", "classv8_1_1_isolate_1_1_suppress_microtask_execution_scope.html", null ],
    [ "v8::Task", "classv8_1_1_task.html", null ],
    [ "v8::TaskRunner", "classv8_1_1_task_runner.html", null ],
    [ "v8::platform::tracing::TraceBuffer", "classv8_1_1platform_1_1tracing_1_1_trace_buffer.html", null ],
    [ "v8::platform::tracing::TraceBufferChunk", "classv8_1_1platform_1_1tracing_1_1_trace_buffer_chunk.html", null ],
    [ "v8::platform::tracing::TraceConfig", "classv8_1_1platform_1_1tracing_1_1_trace_config.html", null ],
    [ "cppgc::TraceDescriptor", "structcppgc_1_1_trace_descriptor.html", null ],
    [ "v8::TracedGlobal< T >", "classv8_1_1_traced_global.html", null ],
    [ "v8::EmbedderHeapTracer::TracedGlobalHandleVisitor", "classv8_1_1_embedder_heap_tracer_1_1_traced_global_handle_visitor.html", null ],
    [ "v8::TracedGlobalTrait< T >", "structv8_1_1_traced_global_trait.html", null ],
    [ "v8::TracedReference< T >", "classv8_1_1_traced_reference.html", null ],
    [ "v8::TracedReferenceBase< T >", "classv8_1_1_traced_reference_base.html", null ],
    [ "v8::platform::tracing::TraceObject", "classv8_1_1platform_1_1tracing_1_1_trace_object.html", null ],
    [ "v8::TracingController::TraceStateObserver", "classv8_1_1_tracing_controller_1_1_trace_state_observer.html", null ],
    [ "v8::EmbedderHeapTracer::TraceSummary", "structv8_1_1_embedder_heap_tracer_1_1_trace_summary.html", null ],
    [ "cppgc::TraceTrait< T >", "structcppgc_1_1_trace_trait.html", null ],
    [ "cppgc::internal::TraceTraitImpl< T, bool >", "structcppgc_1_1internal_1_1_trace_trait_impl.html", null ],
    [ "cppgc::internal::TraceTraitImpl< T, false >", "structcppgc_1_1internal_1_1_trace_trait_impl_3_01_t_00_01false_01_4.html", null ],
    [ "cppgc::internal::TraceTraitImpl< T, true >", "structcppgc_1_1internal_1_1_trace_trait_impl_3_01_t_00_01true_01_4.html", null ],
    [ "v8::platform::tracing::TraceWriter", "classv8_1_1platform_1_1tracing_1_1_trace_writer.html", null ],
    [ "TracingController", null, [
      [ "v8::platform::tracing::TracingController", "classv8_1_1platform_1_1tracing_1_1_tracing_controller.html", null ]
    ] ],
    [ "v8::TracingController", "classv8_1_1_tracing_controller.html", null ],
    [ "true_type", null, [
      [ "cppgc::internal::HasFinalizeGarbageCollectedObject< T, void_t< decltype(std::declval< T >().FinalizeGarbageCollectedObject())> >", "structcppgc_1_1internal_1_1_has_finalize_garbage_collected_object_3_01_t_00_01void__t_3_01decltyb1fe841a93e16892e288bc89fa82e247.html", null ],
      [ "cppgc::internal::IsGarbageCollectedMixinType< T, void_t< typename std::remove_const_t< T >::IsGarbageCollectedMixinTypeMarker > >", "structcppgc_1_1internal_1_1_is_garbage_collected_mixin_type_3_01_t_00_01void__t_3_01typename_01sc69507d8a21a9158d7880f943f2d28f3.html", null ],
      [ "cppgc::internal::IsGarbageCollectedType< T, void_t< typename std::remove_const_t< T >::IsGarbageCollectedTypeMarker > >", "structcppgc_1_1internal_1_1_is_garbage_collected_type_3_01_t_00_01void__t_3_01typename_01std_1_16857dacf9a7c663372c946c0449c1611.html", null ],
      [ "cppgc::internal::IsTraceable< T, void_t< decltype(std::declval< T >().Trace(std::declval< Visitor * >()))> >", "structcppgc_1_1internal_1_1_is_traceable_3_01_t_00_01void__t_3_01decltype_07std_1_1declval_3_01_9b363e26d775c4d015c7fd96282dccd4.html", null ],
      [ "cppgc::internal::IsTraceMethodConst< T, void_t< decltype(std::declval< const T >().Trace(std::declval< Visitor * >()))> >", "structcppgc_1_1internal_1_1_is_trace_method_const_3_01_t_00_01void__t_3_01decltype_07std_1_1decldbaf3d477e31a4e3dae404d71244f764.html", null ],
      [ "cppgc::internal::IsWeak< BasicPersistent< T, internal::WeakPersistentPolicy, LocationPolicy, CheckingPolicy > >", "structcppgc_1_1internal_1_1_is_weak_3_01_basic_persistent_3_01_t_00_01internal_1_1_weak_persistec95343b251fd1128c0ca71638052962a.html", null ],
      [ "cppgc::internal::IsWeak< internal::BasicMember< T, WeakMemberTag, WriteBarrierPolicy, CheckingPolicy > >", "structcppgc_1_1internal_1_1_is_weak_3_01internal_1_1_basic_member_3_01_t_00_01_weak_member_tag_093967881a03d9c319ab8dd0ab33afd56.html", null ]
    ] ],
    [ "v8::TryCatch", "classv8_1_1_try_catch.html", null ],
    [ "v8::UnboundScript", "classv8_1_1_unbound_script.html", null ],
    [ "v8::Unlocker", "classv8_1_1_unlocker.html", null ],
    [ "v8::Unwinder", "classv8_1_1_unwinder.html", null ],
    [ "v8::UnwindState", "structv8_1_1_unwind_state.html", null ],
    [ "v8::String::Utf8Value", "classv8_1_1_string_1_1_utf8_value.html", null ],
    [ "v8::V8", "classv8_1_1_v8.html", null ],
    [ "v8_inspector::V8ContextInfo", "classv8__inspector_1_1_v8_context_info.html", null ],
    [ "v8_inspector::V8Inspector", "classv8__inspector_1_1_v8_inspector.html", null ],
    [ "v8_inspector::V8InspectorClient", "classv8__inspector_1_1_v8_inspector_client.html", null ],
    [ "v8_inspector::V8InspectorSession", "classv8__inspector_1_1_v8_inspector_session.html", null ],
    [ "v8_inspector::V8StackTrace", "classv8__inspector_1_1_v8_stack_trace.html", null ],
    [ "v8_inspector::V8StackTraceId", "structv8__inspector_1_1_v8_stack_trace_id.html", null ],
    [ "v8::String::Value", "classv8_1_1_string_1_1_value.html", null ],
    [ "v8::ValueDeserializer", "classv8_1_1_value_deserializer.html", null ],
    [ "v8::ValueSerializer", "classv8_1_1_value_serializer.html", null ],
    [ "cppgc::Visitor", "classcppgc_1_1_visitor.html", null ],
    [ "v8::JitCodeEvent::wasm_source_info_t", "structv8_1_1_jit_code_event_1_1wasm__source__info__t.html", null ],
    [ "v8::WasmModuleObjectBuilderStreaming", "classv8_1_1_wasm_module_object_builder_streaming.html", null ],
    [ "v8::WasmStreaming", "classv8_1_1_wasm_streaming.html", null ],
    [ "v8::WeakCallbackInfo< T >", "classv8_1_1_weak_callback_info.html", null ],
    [ "v8::WeakCallbackObject< T, P >", "classv8_1_1_weak_callback_object.html", null ],
    [ "cppgc::internal::WeakPersistentPolicy", "structcppgc_1_1internal_1_1_weak_persistent_policy.html", null ],
    [ "v8::WrapperTraits< T >", "classv8_1_1_wrapper_traits.html", null ]
];