var namespacecppgc_1_1internal =
[
    [ "BasicMember", "classcppgc_1_1internal_1_1_basic_member.html", "classcppgc_1_1internal_1_1_basic_member" ],
    [ "BasicPersistent", "classcppgc_1_1internal_1_1_basic_persistent.html", "classcppgc_1_1internal_1_1_basic_persistent" ],
    [ "DijkstraWriteBarrierPolicy", "structcppgc_1_1internal_1_1_dijkstra_write_barrier_policy.html", null ],
    [ "DisabledCheckingPolicy", "classcppgc_1_1internal_1_1_disabled_checking_policy.html", "classcppgc_1_1internal_1_1_disabled_checking_policy" ],
    [ "EatParams", "structcppgc_1_1internal_1_1_eat_params.html", null ],
    [ "EnabledCheckingPolicy", "classcppgc_1_1internal_1_1_enabled_checking_policy.html", "classcppgc_1_1internal_1_1_enabled_checking_policy" ],
    [ "FinalizerTrait", "structcppgc_1_1internal_1_1_finalizer_trait.html", null ],
    [ "FinalizerTraitImpl", "structcppgc_1_1internal_1_1_finalizer_trait_impl.html", null ],
    [ "FinalizerTraitImpl< T, false >", "structcppgc_1_1internal_1_1_finalizer_trait_impl_3_01_t_00_01false_01_4.html", null ],
    [ "FinalizerTraitImpl< T, true >", "structcppgc_1_1internal_1_1_finalizer_trait_impl_3_01_t_00_01true_01_4.html", null ],
    [ "GarbageCollectedBase", "classcppgc_1_1internal_1_1_garbage_collected_base.html", "classcppgc_1_1internal_1_1_garbage_collected_base" ],
    [ "GCInfoTrait", "structcppgc_1_1internal_1_1_g_c_info_trait.html", null ],
    [ "HasFinalizeGarbageCollectedObject", "structcppgc_1_1internal_1_1_has_finalize_garbage_collected_object.html", null ],
    [ "HasFinalizeGarbageCollectedObject< T, void_t< decltype(std::declval< T >().FinalizeGarbageCollectedObject())> >", "structcppgc_1_1internal_1_1_has_finalize_garbage_collected_object_3_01_t_00_01void__t_3_01decltyb1fe841a93e16892e288bc89fa82e247.html", null ],
    [ "IgnoreLocationPolicy", "classcppgc_1_1internal_1_1_ignore_location_policy.html", "classcppgc_1_1internal_1_1_ignore_location_policy" ],
    [ "IsGarbageCollectedMixinType", "structcppgc_1_1internal_1_1_is_garbage_collected_mixin_type.html", null ],
    [ "IsGarbageCollectedMixinType< T, void_t< typename std::remove_const_t< T >::IsGarbageCollectedMixinTypeMarker > >", "structcppgc_1_1internal_1_1_is_garbage_collected_mixin_type_3_01_t_00_01void__t_3_01typename_01sc69507d8a21a9158d7880f943f2d28f3.html", null ],
    [ "IsGarbageCollectedType", "structcppgc_1_1internal_1_1_is_garbage_collected_type.html", null ],
    [ "IsGarbageCollectedType< T, void_t< typename std::remove_const_t< T >::IsGarbageCollectedTypeMarker > >", "structcppgc_1_1internal_1_1_is_garbage_collected_type_3_01_t_00_01void__t_3_01typename_01std_1_16857dacf9a7c663372c946c0449c1611.html", null ],
    [ "IsSubclassOfTemplate", "structcppgc_1_1internal_1_1_is_subclass_of_template.html", null ],
    [ "IsTraceable", "structcppgc_1_1internal_1_1_is_traceable.html", null ],
    [ "IsTraceable< T, void_t< decltype(std::declval< T >().Trace(std::declval< Visitor * >()))> >", "structcppgc_1_1internal_1_1_is_traceable_3_01_t_00_01void__t_3_01decltype_07std_1_1declval_3_01_9b363e26d775c4d015c7fd96282dccd4.html", null ],
    [ "IsTraceMethodConst", "structcppgc_1_1internal_1_1_is_trace_method_const.html", null ],
    [ "IsTraceMethodConst< T, void_t< decltype(std::declval< const T >().Trace(std::declval< Visitor * >()))> >", "structcppgc_1_1internal_1_1_is_trace_method_const_3_01_t_00_01void__t_3_01decltype_07std_1_1decldbaf3d477e31a4e3dae404d71244f764.html", null ],
    [ "IsWeak", "structcppgc_1_1internal_1_1_is_weak.html", null ],
    [ "IsWeak< BasicPersistent< T, internal::WeakPersistentPolicy, LocationPolicy, CheckingPolicy > >", "structcppgc_1_1internal_1_1_is_weak_3_01_basic_persistent_3_01_t_00_01internal_1_1_weak_persistec95343b251fd1128c0ca71638052962a.html", null ],
    [ "IsWeak< internal::BasicMember< T, WeakMemberTag, WriteBarrierPolicy, CheckingPolicy > >", "structcppgc_1_1internal_1_1_is_weak_3_01internal_1_1_basic_member_3_01_t_00_01_weak_member_tag_093967881a03d9c319ab8dd0ab33afd56.html", null ],
    [ "KeepLocationPolicy", "classcppgc_1_1internal_1_1_keep_location_policy.html", "classcppgc_1_1internal_1_1_keep_location_policy" ],
    [ "make_void", "structcppgc_1_1internal_1_1make__void.html", "structcppgc_1_1internal_1_1make__void" ],
    [ "MakeGarbageCollectedTraitInternal", "classcppgc_1_1internal_1_1_make_garbage_collected_trait_internal.html", "classcppgc_1_1internal_1_1_make_garbage_collected_trait_internal" ],
    [ "NoWriteBarrierPolicy", "structcppgc_1_1internal_1_1_no_write_barrier_policy.html", null ],
    [ "PersistentNode", "classcppgc_1_1internal_1_1_persistent_node.html", "classcppgc_1_1internal_1_1_persistent_node" ],
    [ "PersistentRegion", "classcppgc_1_1internal_1_1_persistent_region.html", "classcppgc_1_1internal_1_1_persistent_region" ],
    [ "PrefinalizerRegistration", "classcppgc_1_1internal_1_1_prefinalizer_registration.html", "classcppgc_1_1internal_1_1_prefinalizer_registration" ],
    [ "PreFinalizerRegistrationDispatcher", "classcppgc_1_1internal_1_1_pre_finalizer_registration_dispatcher.html", "classcppgc_1_1internal_1_1_pre_finalizer_registration_dispatcher" ],
    [ "RegisteredGCInfoIndex", "classcppgc_1_1internal_1_1_registered_g_c_info_index.html", "classcppgc_1_1internal_1_1_registered_g_c_info_index" ],
    [ "SentinelPointer", "structcppgc_1_1internal_1_1_sentinel_pointer.html", "structcppgc_1_1internal_1_1_sentinel_pointer" ],
    [ "StrongPersistentPolicy", "structcppgc_1_1internal_1_1_strong_persistent_policy.html", "structcppgc_1_1internal_1_1_strong_persistent_policy" ],
    [ "TraceTraitImpl", "structcppgc_1_1internal_1_1_trace_trait_impl.html", null ],
    [ "TraceTraitImpl< T, false >", "structcppgc_1_1internal_1_1_trace_trait_impl_3_01_t_00_01false_01_4.html", null ],
    [ "TraceTraitImpl< T, true >", "structcppgc_1_1internal_1_1_trace_trait_impl_3_01_t_00_01true_01_4.html", null ],
    [ "WeakPersistentPolicy", "structcppgc_1_1internal_1_1_weak_persistent_policy.html", "structcppgc_1_1internal_1_1_weak_persistent_policy" ]
];